### PR TITLE
Fix #152: handle type alias indexers

### LINKED ISSUE #152: Type aliases don't work as object indexes - crash bug
If I make a file with only this in it:

```
type MyString = string;
type MyObject = {[id: MyString]: string};
```

And run the tool on it, this happens:
```
$ flow-to-ts myfile.js
error processing myfile.js
TypeError: Property name expected type of string but got null
    at Object.validate (/home/nretallack/.config/yarn/global/node_modules/@babel/types/lib/definitions/utils.js:159:13)
    at validateField (/home/nretallack/.config/yarn/global/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at validate (/home/nretallack/.config/yarn/global/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at builder (/home/nretallack/.config/yarn/global/node_modules/@babel/types/lib/builders/builder.js:38:27)
    at Object.TSTypeParameter (/home/nretallack/.config/yarn/global/node_modules/@babel/types/lib/builders/generated/index.js:1182:31)
    at indexers.forEach.indexer (/home/nretallack/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/src/transform.js:564:35)
    at Array.forEach (<anonymous>)
    at Object.exit (/home/nretallack/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/src/transform.js:554:16)
    at NodePath._call (/home/nretallack/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/babel-traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/nretallack/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/babel-traverse/lib/path/context.js:42:17)
```

I suppose https://github.com/Khan/flow-to-ts/issues/108 didn't fix this.

### PR DESCRIPTION
**Pull request by k4b7**
@babel/types added some validation code recently.  I've vendored this package and disabled it in babel-types/lib/builders/builders.js.

### CODE REVIEW

File: babel-types/lib/builders/builder.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    let arg;
+    if (i < countArgs) arg = args[i];
+    if (arg === undefined) arg = (0, _clone.default)(field.default);
+    node[key] = arg;
+    i++;
+  });
+
+  // for (const key of Object.keys(node)) {
+  //   (0, _validate.default)(node, key, node[key]);
+  // }
```
Comment (k4b7) [inline babel-types/lib/builders/builder.js:39]: This was the only change I made.
