### PR TITLE
Wrap function types in parens when processing nullable types

### LINKED ISSUE #197: [Correctness] Maybe functions get incorrectly translated
The following ([see here](https://flow-to-ts.netlify.app/#code=dHlwZSBGb28gPSB7CiAgbmFtZTogc3RyaW5nLAogIG9uQ2hhbmdlPzogPyhzdHJpbmcpID0+IHZvaWQsCn07Cg==&prettier=1&semi=1&singleQuote=0&tabWidth=2&trailingComma=all&bracketSpacing=0&arrowParens=always&printWidth=80&inlineUtilityTypes=0)):
```js
type Foo = {
  name: string,
  onChange?: ?(string) => void,
};
```
Gets incorrectly translated to:
```ts
type Foo = {
  name: string;
  onChange?: (arg0: string) => void | null | undefined;
};
```
The problem is related to operator precedence. The arrow function should to be wrapped in parens:
```ts
type Foo = {
  name: string;
  onChange?: ((arg0: string) => void) | null | undefined;
};
```

### PR DESCRIPTION
**Pull request by k4b7**
This fixes #197.

### CODE REVIEW

File: src/transform.js [hunk 1]
```diff
@@ -250,12 +250,18 @@ const transform = {
...
       path.replaceWith(
         t.tsUnionType([
-          // conditionally unwrap TSTypeAnnotation nodes
-          t.isTSTypeAnnotation(typeAnnotation)
-            ? typeAnnotation.typeAnnotation
-            : typeAnnotation,
+          // conditionally wrap function types in parens
+          t.isTSFunctionType(unwrappedType)
+            ? t.tsParenthesizedType(unwrappedType)
+            : unwrappedType,
```
Comment (k4b7) [inline src/transform.js:264]: I'm not really sure why the babel AST has a specific node to parenthesize types, but that's apparently how this should be structured.  I checked astexplorer.net.
